# Generated by Django 5.1.4 on 2025-01-08 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='currency',
            field=models.CharField(choices=[('KSH', 'Kenyan Shilling'), ('EURO', 'Euro'), ('POUND', 'Pound Sterling'), ('DOLLAR', 'US Dollar')], default='POUND', max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=25),
        ),
    ]
